### PR TITLE
Added check for empty records

### PR DESCRIPTION
**Pull request by andre-ferreira-qlik**
I've noticed that if there are empty records that a NaN was added. The console log can be avoided of course, but wanted your opinion about this.

### CODE REVIEW

**Comment by stefanwalther** [comment]
Yeah, this is a good one, will incorporate it (without the console.info)

**Comment by andre-ferreira-qlik** [comment]
Cheers. I'll take it out later so you can merge.

**Comment by andre-ferreira-qlik** [comment]
Should be good to go now

**Comment by andre-ferreira-qlik** [comment]
qNullSuppression in 1.1 is not avoiding - and NaN, I've added a new check with qIsNull to avoid possible issues

**Comment by stefanwalther** [comment]
Accepted in ed23080ee62935bb296ef5ffeed3bbe397300974, thx

**Pull request closed without merging**
