### PR TITLE
Update swr-calendarview.js

### PR DESCRIPTION
**Pull request by qliktap**
fix to send the correct width to renderChart and detect when it needs to redraw due to the changes in screen size.

### CODE REVIEW

**Comment by stefanwalther** [comment]
Travis build faild, but no problem, I'll figure out, thx!

**Comment by stefanwalther** [comment]
Hi, I'll reject the pull request because there are some problems with it, but if you don't mind I'll just implement the idea and mention you, because you are absolutely right, your approach works better. Let me know if this fixes your problem ...

**Comment by qliktap** [comment]
Yeah absolutely! As long as it works at the end of the day then it's all good.

**Comment by stefanwalther** [comment]
Done, give it a try and let me know.

**Pull request merged**
